# This is a basic workflow to help you get started with Actions

name: SSH_CONNECT

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.COMMON_PEM_KEY }}
#          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo hello connect
        
      
    
