# This is a basic workflow to help you get started with Actions

name: SSH_CONNECT

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.HOST_USER}}
          KEY: ${{secrets.COMMON_PEM_KEY}}
          PORT: ${{secrets.PORT}}
          script: |
            echo hello connect
        
      
    
