# This is a basic workflow to help you get started with Actions

name: SSH_CONNECT

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Login to Cotainer Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: JIB container publish
        run: ./gradlew jib

      - name: Deploy to Docker swarm
        uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: ${{ secrets.REMOTE_DOCKER_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          compose_file: docker-compose-prod.yml
          pull: true
          build: true
