# This is a basic workflow to help you get started with Actions

name: SSH_CONNECT

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Login to Cotainer Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: JIB container publish
        run: ./gradlew jib

      - name: create file
        run: | 
          pwd
          test_text > .env
#      - name: Deploy to Docker swarm
#        uses: pcjun97/action-setup-docker-host-ssh@v1
#        with:
#          host: ${{ secrets.REMOTE_DOCKER_HOST }}
#          user: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
#      - run: |
#          docker login -u ${{ secrets.ACCESS_KEY }} ${{ secrets.DOCKER_REGISTRY }} -p ${{ secrets.SECRET_KEY }}
#
#          docker ps -qa
#
#          docker rm -f $(docker ps -qa)
#          docker image rm -f $(docker image ls -q)
#
#          docker-compose -f docker-compose-prod.yml up -d
